### ISSUE TITLE
Code release date

### ISSUE THREAD

**Issue by zdyshine** [claudiom4sir/StableVSR#1]
Could you tell an approximate date for code realease so that I can start experimenting too? Thanks.

**Comment by claudiom4sir** [comment]
I hope to release it within two weeks. Thanks for your interest!

**Comment by zdyshine** [comment]
Still have a plan to release the code?

**Comment by claudiom4sir** [comment]
Hi, sorry for not publishing the code yet, but I was very busy on other projects.
I'll publish it for sure, but now I can't tell you exactly when.

**Comment by ghost** [comment]
> Hi, sorry for not publishing the code yet, but I was very busy on other projects. I'll publish it for sure, but now I can't tell you exactly when.

What is this trend of releasing AI projects on GitHub without code? GitHub was designed for open source code to be shared. If you only use it as a marketing platform, you make yourself rather untrustworthy. You can make a lot of claims, but without evidence they remain claims.

**Comment by claudiom4sir** [comment]
Hi all, the code has been released!
