### ISSUE TITLE
How to load my own trained weights to run tests？

### ISSUE THREAD

**Issue by wjaycyf** [claudiom4sir/StableVSR#11]
Hello, I successfully ran the training code and generated the model weights as follows，
![image](https://github.com/user-attachments/assets/14b3b0b7-ce3d-4b43-9918-96cbd1fd6f46)
My confusion is that when I execute the test: python test.py --in_path YOUR_PATH_TO_LR_SEQS --out_path YOUR_OUTPUT_PATH --num_inference_steps 50, how do I load my own completed trained model? How should I specify in the test code and which files to specify to complete the test?
![image](https://github.com/user-attachments/assets/ad3e09b4-8cfb-4aaf-b57f-44c41f702a2f)

**Comment by claudiom4sir** [comment]
Hi,

you can add the following lines:
```
from diffusers import ControlNetModel
controlnet_model = ControlNetModel.from_pretrained(your_path_to_ckpt/checkpoint-20000, subfolder='controlnet')
```
and replace
```
pipeline = StableVSRPipeline.from_pretrained(model_id)
```
with
```
pipeline = StableVSRPipeline.from_pretrained(model_id, controlnet=controlnet_model)
```
I forgot to add this option in the test script. I have just updated the code to support this operation.

**Comment by wjaycyf** [comment]
> 你好，
> 
> 您可以添加以下几行：
> 
> ```
> from diffusers import ControlNetModel
> controlnet_model = ControlNetModel.from_pretrained(your_path_to_ckpt/checkpoint-20000, subfolder='controlnet')
> ```
> 
> 并替换
> 
> ```
> pipeline = StableVSRPipeline.from_pretrained(model_id)
> ```
> 
> 和
> 
> ```
> pipeline = StableVSRPipeline.from_pretrained(model_id, controlnet=controlnet_model)
> ```
> 
> 我忘记在测试脚本中添加此选项。我刚刚更新了代码以支持此操作。

I understand, thank you very much!

**Comment by wjaycyf** [comment]
Hello, I have successfully tested the model based on your modified code, but found that, the test results do not contain the evaluation metrics, can you please provide the calculation metrics in the code? Looking forward to your reply.
![image](https://github.com/user-attachments/assets/5bfc5718-8b1f-49c0-a7e5-cbe317322c61)
@claudiom4sir

**Comment by claudiom4sir** [comment]
Refer to issue #12

**Comment by chahu-12** [comment]
> Hello, I successfully ran the training code and generated the model weights as follows， ![image](https://private-user-images.githubusercontent.com/86214187/381833574-14b3b0b7-ce3d-4b43-9918-96cbd1fd6f46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMTMxNzcsIm5iZiI6MTczNDAxMjg3NywicGF0aCI6Ii84NjIxNDE4Ny8zODE4MzM1NzQtMTRiM2IwYjctY2UzZC00YjQzLTk5MTgtOTZjYmQxZmQ2ZjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDE0MTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNjhkNzNlYzA5MGZiMTFlYmRiYjI0NWZmZWI3MGNiNjFlZjg0N2UxYzQ0ZGNmMjU0ZGZhMzI5N2IxMzgwYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I8IRQVJbcCaum3DDsd7UKfqUiQGxHUxjQHTBLZxVIvI) My confusion is that when I execute the test: python test.py --in_path YOUR_PATH_TO_LR_SEQS --out_path YOUR_OUTPUT_PATH --num_inference_steps 50, how do I load my own completed trained model? How should I specify in the test code and which files to specify to complete the test? ![image](https://private-user-images.githubusercontent.com/86214187/381833639-ad3e09b4-8cfb-4aaf-b57f-44c41f702a2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMTMxNzcsIm5iZiI6MTczNDAxMjg3NywicGF0aCI6Ii84NjIxNDE4Ny8zODE4MzM2MzktYWQzZTA5YjQtOGNmYi00YWFmLWI1N2YtNDRjNDFmNzAyYTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDE0MTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ODAyNThhM2NiYWMzZTNmZGQwZmU0YmU2OTFiM2YzMjM2NTc4YWY5ZjdlZjM0OTg5MzljMmI0ZGEwMjU2Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F2aXqM-STHVOaeN8nHj_UoCnw1Evstu_Anacb2sDmIs)



> Hello, I successfully ran the training code and generated the model weights as follows， ![image](https://private-user-images.githubusercontent.com/86214187/381833574-14b3b0b7-ce3d-4b43-9918-96cbd1fd6f46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMTMxNzcsIm5iZiI6MTczNDAxMjg3NywicGF0aCI6Ii84NjIxNDE4Ny8zODE4MzM1NzQtMTRiM2IwYjctY2UzZC00YjQzLTk5MTgtOTZjYmQxZmQ2ZjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDE0MTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNjhkNzNlYzA5MGZiMTFlYmRiYjI0NWZmZWI3MGNiNjFlZjg0N2UxYzQ0ZGNmMjU0ZGZhMzI5N2IxMzgwYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I8IRQVJbcCaum3DDsd7UKfqUiQGxHUxjQHTBLZxVIvI) My confusion is that when I execute the test: python test.py --in_path YOUR_PATH_TO_LR_SEQS --out_path YOUR_OUTPUT_PATH --num_inference_steps 50, how do I load my own completed trained model? How should I specify in the test code and which files to specify to complete the test? ![image](https://private-user-images.githubusercontent.com/86214187/381833639-ad3e09b4-8cfb-4aaf-b57f-44c41f702a2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMTMxNzcsIm5iZiI6MTczNDAxMjg3NywicGF0aCI6Ii84NjIxNDE4Ny8zODE4MzM2MzktYWQzZTA5YjQtOGNmYi00YWFmLWI1N2YtNDRjNDFmNzAyYTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDE0MTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ODAyNThhM2NiYWMzZTNmZGQwZmU0YmU2OTFiM2YzMjM2NTc4YWY5ZjdlZjM0OTg5MzljMmI0ZGEwMjU2Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F2aXqM-STHVOaeN8nHj_UoCnw1Evstu_Anacb2sDmIs)

Did you train with 4 GPUs? Can it be trained with 2 GPUs?

**Comment by claudiom4sir** [comment]
> Did you train with 4 GPUs?

Yes

> Can it be trained with 2 GPUs?

Yes, just change the option `GPUS` (set your GPUs, such as 0 and 1) in `train.sh`

**Comment by chahu-12** [comment]
> > Did you train with 4 GPUs?
> 
> Yes
> 
> > Can it be trained with 2 GPUs?
> 
> Yes, just change the option `GPUS` (set your GPUs, such as 0 and 1) in `train.sh`

Thank you!

**Comment by chahu-12** [comment]
> > Did you train with 4 GPUs?
> 
> Yes
> 
> > Can it be trained with 2 GPUs?
> 
> Yes, just change the option `GPUS` (set your GPUs, such as 0 and 1) in `train.sh`

Can I run the train.py file directly without going through train.sh?

**Comment by claudiom4sir** [comment]
> Can I run the train.py file directly without going through train.sh?

Yes you can, but it is not recommended since you have to specify many parameters in the command line.
