### ISSUE TITLE
How to calculate the evaluation metrics in your paper？

### ISSUE THREAD

**Issue by wjaycyf** [claudiom4sir/StableVSR#12]
Hello, I have successfully tested the model based on your modified code, but found that, the test results do not contain the evaluation metrics, can you please provide the calculation metrics in the code? Looking forward to your reply.
![image](https://github.com/user-attachments/assets/5176be32-7886-4e6f-9a6f-8c27869ddcb9)

**Comment by claudiom4sir** [comment]
Hi,

I will upload the evaluation script soon.

In the meantime, I can give you practical suggestions on how to compute the metrics.

For PSNR, SSIM and LPIPS, I used `torchmetrics`.
For DISTS, I used the official implementation available [here](https://github.com/dingkeyan93/DISTS).
For MUSIQ, CLIP-IQA and NIQE, I used `pyiqa`.
For tLP and tOF, I implemented them according to this [paper](https://arxiv.org/abs/1811.09393). tLP is just the difference between LPIPS of two consecutive frames, while tOF is the difference between the optical flows computed on output frames and reference frames . You can use `get_flow` available in [flow_utils.py](https://github.com/claudiom4sir/StableVSR/blob/main/util/flow_utils.py) for this.

**Comment by claudiom4sir** [comment]
Hi @wjaycyf 
I've just added `eval.py`
