### ISSUE TITLE
Code or script to calculate the paper metrics

### ISSUE THREAD

**Issue by mingheyuemankong** [claudiom4sir/StableVSR#13]
Awesome job! Hello, I was executing the test script and realized that the codebase does not seem to provide the code or script to calculate the metrics mentioned in the paper. I would appreciate if you could provide this part.

Also, the paper mentions the Vimeo-90K dataset, if I want to train and test on the Vimeo-90K dataset, how should I modify the code to load that dataset? Can you provide more guidance? Thanks.

**Comment by claudiom4sir** [comment]
Hi,

for the evaluation script, you can refer to issue #12.

For Video-90K training and testing, I will upload the necessary files soon.

Thanks for your interest!

**Comment by claudiom4sir** [comment]
Hi @mingheyuemankong, I'm sorry but I cannot directly provide the code for Vimeo-90K. You may refer to issue #16 for details on its implementation.
