### ISSUE TITLE
Question about Unet pretrained weight

### ISSUE THREAD

**Issue by jamichss** [claudiom4sir/StableVSR#14]
Thank you for your impressive work! Your research has been extremely helpful to me, and I am honored to have the opportunity to delve deeper into it. I have a question regarding the implementation of stableVSR. From my understanding, training is conducted only on the controlnet, is that correct? However, I noticed that the unet weights you provided differ from those from sd-x4. Could there be something that I have overlooked? Thank you for your patience in answering.

**Comment by claudiom4sir** [comment]
Hi @00757039,
> From my understanding, training is conducted only on the controlnet, is that correct? However, I noticed that the unet weights you provided differ from those from sd-x4. Could there be something that I have overlooked?

The UNet weights provided in Huggingface repo are from a fine-tuned UNet. Specifically, the original SDx4Upscaler UNet has been fine-tuned on REDS to improve the quality of single-image super-resolution, considering video frames as single images and using empty-string prompts to remove text dependencies.

**Comment by jamichss** [comment]
OK! Thanks for your explanation!
