### ISSUE TITLE
About training time and details.

### ISSUE THREAD

**Issue by Walnutes** [claudiom4sir/StableVSR#15]
Thank you for your excellent work!

I have a question regarding the training details of your model. Was the model trained exclusively on the REDS dataset and then tested on REDS4 and Vimeo90K-T for super-resolution? Additionally, could you please share how long it takes to complete the training under the computational resources and hyperparameter settings described in the paper? If separate training is required for the two datasets, could you kindly provide the training time for each?

Looking forward to your response!

**Comment by claudiom4sir** [comment]
Hi @Walnutes,

>  Was the model trained exclusively on the REDS dataset and then tested on REDS4 and Vimeo90K-T for super-resolution?

No, for Vimeo90K-T a different model was trained using Vimeo90K dataset. The training setup is exactly the same, only the dataset is different.

>Additionally, could you please share how long it takes to complete the training under the computational resources and hyperparameter settings described in the paper? If separate training is required for the two datasets, could you kindly provide the training time for each?

According to the setup described in the paper, training a new model requires about 15 hours to complete 20K steps, both for REDS and Vimeo90K.

**Comment by Walnutes** [comment]
Thanks for your detailed reply!
