### ISSUE TITLE
Public online demo

### ISSUE THREAD

**Issue by Elena324-syber** [claudiom4sir/StableVSR#2]
Good afternoon. Thank you for your amazing work. I am impressed with the significant improvement in quality over other AI models for video enhancement. 
Do you plan to make a public demo on HuggingFace, Replicate, or Google Colab for example?
Thank you very much for your attention!

**Comment by claudiom4sir** [comment]
Hi! Maybe in the future, but I just plan to release the code and pretrained models for now. Thanks for your interest!

**Comment by Elena324-syber** [comment]
Thank you, I'm looking forward to it!

**Comment by mrartemev-oss** [comment]
@claudiom4sir hey! Any updates on releasing the code and models?

**Comment by claudiom4sir** [comment]
Hi @Elena324-syber @mrartemevmorphic , the code has been released!
