### ISSUE TITLE
Sizes of tensors must match except in dimension 1.

### ISSUE THREAD

**Issue by DDDaxing** [claudiom4sir/StableVSR#4]
```
 latent_model_input = torch.cat([latent_model_input, image], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 270 but got size 1080 for tensor number 1 in the list.
```
Hi authors,
Thank you for releasing the code. I have encountered the error using your inference code.

The image dimension is: torch.Size([1, 3, 1080, 1920])
However, latent dimension is: torch.Size([1, 4, 270, 480])

How should I fix it? Thank you

**Comment by claudiom4sir** [comment]
Hi, is 1920x1080 the shape of your low-resolution video?

Can you check the size of `latents[0]` after this code (line 934)?

`latents = [self.prepare_latents(
                    batch_size * num_images_per_prompt,
                    num_channels_latents,
                    height,
                    width,
                    prompt_embeds.dtype,
                    device,
                    generator
                ) for _ in range(len(images))]`

Please also check the size of `images[0]`, `height` and `width`.

Thanks

**Comment by DDDaxing** [comment]
> Hi, is 1920x1080 the shape of your low-resolution video?
> 
> Can you check the size of `latents[0]` after this code (line 934)?
> 
> `latents = [self.prepare_latents( batch_size * num_images_per_prompt, num_channels_latents, height, width, prompt_embeds.dtype, device, generator ) for _ in range(len(images))]`
> 
> Please also check the size of `images[0]`, `height` and `width`.
> 
> Thanks

Hi author,
Right, my low-resolution video is shape of 1920x1080 and I have changed the scale_factor to 1 (at line 900) due to memory.

The dimensions are as follows:

```
images[0]: torch.Size([1, 3, 1080, 1920])
height: 1080 
width: 1920
latents[0]: torch.Size([1, 4, 270, 480])
```

Seems related to the `scale_factor`.

**Comment by claudiom4sir** [comment]
Ok, now the problem is clear.

A simple trick is to change line 958 with `forward_flows, backward_flows = self.compute_flows(of_model, images, rescale_factor=0.25)`. In this way, optical flow is computed on the low-resolution frames and then it is upscaled to target resolution, which is required in line 974.

I'm not sure how will be the outcome, as direct flow upscaling may introduce artifacts. You can also change line 959 with ` interp_mode = 'bilinear'` to use it for warping and not the "nearest" mode.

**Comment by claudiom4sir** [comment]
I forgot to tell you to set again `scale_factor=4`. Let me know if It works 😀

**Comment by DDDaxing** [comment]
> Ok, now the problem is clear.
> 
> A simple trick is to change line 958 with `forward_flows, backward_flows = self.compute_flows(of_model, images, rescale_factor=0.25)`. In this way, optical flow is computed on the low-resolution frames and then it is upscaled to target resolution, which is required in line 974.
> 
> I'm not sure how will be the outcome, as direct flow upscaling may introduce artifacts. You can also change line 959 with ` interp_mode = 'bilinear'` to use it for warping and not the "nearest" mode.

Hi author,
Thanks for your detailed reply. 

If I change the scale_factor=4, it will `CUDA out of memory` at `upscaled_images = [F.interpolate(image, scale_factor=4, mode='bicubic') for image in images]` line 🤣 My GPU is A100 40G

For test, I resized my input image to (480,270), which works fine at your original settings `scale_factor=4, of_rescale_factor=1`. However, if I changed the `of_rescale_factor ` to 0.5, it will `CUDA out of memory` again... I don't know why the optical flow will take much memory...

I noticed that the `scale_factor` must be 4 may due to the `vae_scale_factor`, which related to the `length of block_out_channels`. Thus the `vae_scale_factor ` is 4 not 8 as in original SD VAE. Can you please kindly explain why you only use 3 level `block_out_channels`?

If in this setting, I think we can only upscale the input to 4x, not support other scales, is it right?
BTW, will you provide the tiled version later? Beg my short GPU memory...

**Comment by claudiom4sir** [comment]
> If I change the scale_factor=4, it will CUDA out of memory at upscaled_images = [F.interpolate(image, scale_factor=4, mode='bicubic') for image in images] line 🤣 My GPU is A100 40G

It is probably due to your video length, as you store a lot of huge tensors. I never tried with video longer than 100 frames and a target resolution higher than 1280x720 as my GPU limit is 24G. 

> For test, I resized my input image to (480,270), which works fine at your original settings scale_factor=4, of_rescale_factor=1. However, if I changed the of_rescale_factor  to 0.5, it will CUDA out of memory again... I don't know why the optical flow will take much memory...

I also see RAFT explodes with that resolution. You could try `raft_small` instead of `raft_large`. It shouldn't change the outcome too much but it may work. 

>  I noticed that the scale_factor must be 4 may due to the vae_scale_factor, which related to the length of block_out_channels. Thus the vae_scale_factor  is 4 not 8 as in original SD VAE. Can you please kindly explain why you only use 3 level block_out_channels?

Yes, I used the VAE of SDx4Upscaler, which has x4 scale_factor instead of 8. This is because just encoding-decoding HR videos using the original SD VAE introduces detail loss and temporal inconsistency. I noticed big differences between input HR frames and SD VAE output, probably due to the high compression at the bottleneck. Instead, with the SDx4Upscaler VAE this difference was negligible.

> If in this setting, I think we can only upscale the input to 4x, not support other scales, is it right?
BTW, will you provide the tiled version later? Beg my short GPU memory...

With my settings, only x4 upscaling is supported since upscaling is performed by the VAE decoder. For higher upscaling, such as x8, you should change the VAE. It is quite easy by code, but the denoising UNet + ControlNet probably require a fine-tuning as the latent space is different. Maybe in the future I'll implement the tiled version, but it isn't in my plan for now.

**Comment by DDDaxing** [comment]
> > If I change the scale_factor=4, it will CUDA out of memory at upscaled_images = [F.interpolate(image, scale_factor=4, mode='bicubic') for image in images] line 🤣 My GPU is A100 40G
> 
> It is probably due to your video length, as you store a lot of huge tensors. I never tried with video longer than 100 frames and a target resolution higher than 1280x720 as my GPU limit is 24G.
> 
> > For test, I resized my input image to (480,270), which works fine at your original settings scale_factor=4, of_rescale_factor=1. However, if I changed the of_rescale_factor  to 0.5, it will CUDA out of memory again... I don't know why the optical flow will take much memory...
> 
> I also see RAFT explodes with that resolution. You could try `raft_small` instead of `raft_large`. It shouldn't change the outcome too much but it may work.
> 
> > I noticed that the scale_factor must be 4 may due to the vae_scale_factor, which related to the length of block_out_channels. Thus the vae_scale_factor  is 4 not 8 as in original SD VAE. Can you please kindly explain why you only use 3 level block_out_channels?
> 
> Yes, I used the VAE of SDx4Upscaler, which has x4 scale_factor instead of 8. This is because just encoding-decoding HR videos using the original SD VAE introduces detail loss and temporal inconsistency. I noticed big differences between input HR frames and SD VAE output, probably due to the high compression at the bottleneck. Instead, with the SDx4Upscaler VAE this difference was negligible.
> 
> > If in this setting, I think we can only upscale the input to 4x, not support other scales, is it right?
> > BTW, will you provide the tiled version later? Beg my short GPU memory...
> 
> With my settings, only x4 upscaling is supported since upscaling is performed by the VAE decoder. For higher upscaling, such as x8, you should change the VAE. It is quite easy by code, but the denoising UNet + ControlNet probably require a fine-tuning as the latent space is different. Maybe in the future I'll implement the tiled version, but it isn't in my plan for now.

Thank you for your detailed reply author.

I have changed my input size to fit the model and now it works. However I found that super-resolution effect is not obvious. It is almost the same as that before the SR. Are there any parameters that will affect the results so that I can tune them to get promising results? Thank you.

**Comment by claudiom4sir** [comment]
> However I found that super-resolution effect is not obvious. It is almost the same as that before the SR.

It may depend on your target resolution. I tried this model to upscale video from other VSR datasets and everything seemed fine. However, the input resolution was always 320x180, more or less. Evaluation on much higher resolution may behave differently.

>Are there any parameters that will affect the results so that I can tune them to get promising results?

You can try changing the number of inference steps or the guidance scale (in this case add `image = torch.cat([image] * 2) if do_classifier_free_guidance else image` before `latent_model_input = torch.cat([latent_model_input, image], dim=1)`). Take also a look at line 719 (`__call__` arguments) to see if something can be useful.
