### ISSUE TITLE
NotADirectoryError

### ISSUE THREAD

**Issue by AIisCool** [claudiom4sir/StableVSR#5]
`python test.py --in_path "C:/StableVSR/input/2/" --out_path "C:/StableVSR/output/" --num_inference_steps 50`

Set to a folder with png frames of a video sequence but I get:
`NotADirectoryError: [WinError 267] The directory name is invalid: 'C:/StableVSR/input/2/00019103.png'`

**Comment by claudiom4sir** [comment]
Hi,
It's because you have to specify a directory containing video sequences, not a directory containing frames. In your case, just remove `2/` from `--in_path`.
