### ISSUE TITLE
torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by jamichss** [claudiom4sir/StableVSR#6]
Hello, I used the test command you provided and tested it on the REDS4 dataset, but I encountered a **torch.cuda.OutOfMemoryError**. During the denoising steps, the memory required is approximately 35.5 GB, and the issue occurs when executing line 1069 in **stablevsr_pipeline**:

```python
images = [self.vae.decode(latent / self.vae.config.scaling_factor, return_dict=False)[0] for latent in latents]
```

The error happens at this point. I am using an RTX A6000 with 48 GB of memory. Could you please provide some insights into what might be causing this issue? Thanks!

**Comment by claudiom4sir** [comment]
Hello, I have a Quadro RTX 6000 with 24 GB and everything works fine. 
<img width="236" alt="Untitled" src="https://github.com/user-attachments/assets/61be1260-d2fc-4bc9-af62-cce753854781">
Is the size of your input frames 320x180? If so, I don't know what's happening...

**Comment by WLuLi** [comment]
Hello, I also encountered a **torch.cuda.OutOfMemoryError** when running test.py, at a input resolution of 320x180.  It occurs when executing line 973 in **stablevsr_pipeline**:
```
x0_est = self.vae.decode(x0_est / self.vae.config.scaling_factor, return_dict=False)[0]  # convert x0_est to RGB
```
Could you please share any potential adjustments or optimizations that might help resolve this issue? Thank you for your time and support!

**Comment by claudiom4sir** [comment]
Hello, I've never had `torch.cuda.OutOfMemoryError` at that resolution. First, make sure all libraries correspond to the requirements.txt. I suggest you detect and remove from memory some variables that are only used for specific operations, such as `upscaled_images` that are only used for optical flow computation. Simply removing it saves about 1.6GB. You could also move variables in and out from GPU, as each denoising or VAE decoding operation only requires variables related to the current frame and the previous/next frame. This saves memory but increases inference time.

**Comment by GraceZhuuu** [comment]
I also encountered the same problem, and my device is 3090 with 24GB 
![image](https://github.com/user-attachments/assets/7ca9ab6f-c817-4207-8011-e62eada3660c)

**Comment by claudiom4sir** [comment]
Hi, 12.36 GB more is a lot... 

Do you have this problem at the beginning of the denoising process or do you see it after some denoising step? You should see a progress bar from 1 to 5000 (i.e. 50 steps for 100 frames).

Can you check the size of `x0_est` before executing that line?

It may be related to different library versions. I just updated the readme file with conda commands. Can you try it? I just tried it and everything works, I use 14.5GB of memory as expected. Thanks.

**Comment by GraceZhuuu** [comment]
```
x0_est.shape: torch.size([1, 4, 180, 320])
```
And it  failed at the beginning, when the progress bar was at 1.
haven’t verify your modification.

**Comment by claudiom4sir** [comment]
> x0_est.shape: torch.size([1, 4, 180, 320])

The size is correct.

> haven’t verify your modification.

Ok, so please try it and let me know, thanks.

**Comment by claudiom4sir** [comment]
As it seems you are having problems during attention, try to add `pipeline.enable_xformers_memory_efficient_attention()` after `pipeline = pipeline.to(device)` at line 38 of `test.py`.

**Comment by WLuLi** [comment]
> As it seems you are having problems during attention, try to add `pipeline.enable_xformers_memory_efficient_attention()` after `pipeline = pipeline.to(device)` at line 38 of `test.py`.

Adding pipeline.enable_xformers_memory_efficient_attention() at line 38 worked perfectly. The memory usage is now around 14.6GB with an input resolution of 320x180. I really appreciate your help!

**Comment by claudiom4sir** [comment]
@WLuLi great news! It seems I'm using efficient attention even without calling it explicitly. I updated the test script.
